### ISSUE TITLE
Cannot start Lavagna on Ubuntu 14.04

### ISSUE THREAD

**Issue by 0ptimus** [digitalfondue/lavagna#10]
Tried running Lavagna on my Ubuntu 14.04 server and got the errors below when trying to launch with ./lavagna.sh (I have MySQL 5.5, java version 1.7.0_75 and have installed libmysql-java)...

Note: database called "lavagna" was created in MySQL with user "someuser" granted ALL privileges.
....
./lavagna.sh: line 54: -Ddatasource.dialect=MYSQL: command not found
./lavagna.sh: line 55: -Ddatasource.url=jdbc:mysql://localhost:3306/lavagna: No such file or directory
./lavagna.sh: line 61: -Ddatasource.username=someuser: command not found

**Comment by syjer** [comment]
Uh, strange, it seems that it's executing each line, the command should be a single line, that's why there is a '\' character, as you can see from: https://github.com/digitalfondue/lavagna/blob/master/src/assembly/lavagna.sh

If you have removed the '\', you should put them.

**Comment by syjer** [comment]
(and you don't need to install libmysql-java, everything is included out of the box in lavagna :))

**Comment by 0ptimus** [comment]
Thanks, somehow I had removed the '\'s.  Now I started and get a Jetty error.
![lavagna_jetty_error](https://cloud.githubusercontent.com/assets/1253770/9252636/5b35ae50-418e-11e5-9b93-930cec0a2a5d.jpg)

**Comment by syjer** [comment]
Hi,

You must configure lavagna, go to the /setup page, as described in the setup section of the manual: http://help.lavagna.io/02-install/02-03-setup.html

**Comment by 0ptimus** [comment]
Thank you, I was able to complete set up.
