### ISSUE TITLE
Email Ticket Question

### ISSUE THREAD

**Issue by c0mputerking** [digitalfondue/lavagna#100]
I read the doc below which helped me out but i still have a question/problem to ask.
https://github.com/digitalfondue/lavagna/blob/master/src/main/stampo/doc/03-use-lavagna/03-12-ticket-mail.en.peb.md

This is my question I have 2 projects lets call them projectA and projectB, and would like to use one email address suppport@projectA for both if possible due to limited number of emails available.  

As stated above I have setup one email account called support@projectA.com which has aliases of support@projectA.com and support@projectB.com.  Next I go to project mail settings and enter in the same support@projectA email username and password on the inbound and outbound mail config screens for both projectA and projectB.  Then i enter ticket config for projectA and use support@projectA.com, and put it into the toDO column of ProjectA.  Next for projectB i enter support@projectB.com and put it into the toDO column of ProjectB  

Everything works as expected for projectA but projectB also goes into the toDO column of projectA.  So my question is can this be done or do i need another email account setup for each project?

**Comment by SitoCH** [comment]
I think that it may be due to this method in MailTicketService:
https://github.com/digitalfondue/lavagna/blob/d41e84d3835cc96064ccc1cedc60786ded185086/src/main/java/io/lavagna/service/MailTicketService.java#L197

Can you provide the e-mail headers so we can see what header is triggering the check?

**Comment by c0mputerking** [comment]
I feel a bit nervous posting this here, not sure why as this info gets sent back and forth everytime i send an email message ... but here is the mail header as requested
 
> Return-Path: ryan.computerking@gmail.com
> Received: from mx2.computerking.ca (LHLO mx2.computerking.ca) (172.16.0.20)
>  by mx2.computerking.ca with LMTP; Sun, 4 Mar 2018 23:27:26 -0700 (MST)
> Received: from localhost (localhost.localdomain [127.0.0.1])
> 	by mx2.computerking.ca (Postfix) with ESMTP id 92A4EA336E3
> 	for <support@computerking.ca>; Sun,  4 Mar 2018 23:27:26 -0700 (MST)
> X-Virus-Scanned: amavisd-new at mx2.computerking.ca
> X-Spam-Flag: NO
> X-Spam-Score: -2.619
> X-Spam-Level:
> X-Spam-Status: No, score=-2.619 required=6 tests=[BAYES_00=-1.9,
> 	DKIM_SIGNED=0.1, DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1,
> 	DMARC_PASS_NONE=-0.6, FREEMAIL_FROM=0.001, HTML_MESSAGE=0.001,
> 	RCVD_IN_MSPIKE_H3=-0.01, RCVD_IN_MSPIKE_WL=-0.01, SPF_PASS=-0.001]
> 	autolearn=ham autolearn_force=no
> Authentication-Results: mx2.computerking.ca (amavisd-new);
> 	dkim=pass (2048-bit key) header.d=gmail.com
> Received: from mx2.computerking.ca ([127.0.0.1])
> 	by localhost (mx2.computerking.ca [127.0.0.1]) (amavisd-new, port 10024)
> 	with ESMTP id Ud8GK8rK_-a0 for <support@computerking.ca>;
> 	Sun,  4 Mar 2018 23:27:24 -0700 (MST)
> Received: from mail-qk0-f180.google.com (mail-qk0-f180.google.com [209.85.220.180])
> 	by mx2.computerking.ca (Postfix) with ESMTPS id ADF22A336C7
> 	for <support@reddhart.ca>; Sun,  4 Mar 2018 23:27:24 -0700 (MST)
> Received: by mail-qk0-f180.google.com with SMTP id y137so19363293qka.4
>         for <support@reddhart.ca>; Sun, 04 Mar 2018 22:27:16 -0800 (PST)
> DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
>         d=gmail.com; s=20161025;
>         h=mime-version:from:date:message-id:subject:to;
>         bh=2JfFzDugjgK5z0fPIcEPmwOa7yMNF/tn+xVoFbX/37M=;
>         b=Ux2eoL9hxOy0NBftZmonUb9Our/1LRnqqhQ4vc0awZQiVcaoKd5pd39f8eVkC17YW2
>          nDStCY1CUUilMtKKw6Q/kYqbkKozgraf5POyJt2FF6LJ4f9W4Lz6F2vV3SCh0H97bmCm
>          I2xgWmzHFwbHLQN84wcyFoJsrfb/sxBw5WJ6Pnmguw6FfjjF/SUsDsVKtLzQ7oVa7tbP
>          a7QV2uhfTVdyG8byt7xooku/ojvB6XdpHI/ijhA+lwQ8qGMYk3sJ9GksHsl+WYc7wm9/
>          JlZpw2g8Md1+AcJY8tMKbITmX17LtE+I+oP8vlF6DbpoSpsGzQP8e9OY2p8tzi5F0snV
>          7cBQ==
> X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
>         d=1e100.net; s=20161025;
>         h=x-gm-message-state:mime-version:from:date:message-id:subject:to;
>         bh=2JfFzDugjgK5z0fPIcEPmwOa7yMNF/tn+xVoFbX/37M=;
>         b=j9ABFGYBMmQaQ8khgONa0+RzrYbCmF7lWn0NanGX4tGZEEW+J8qwdqj98WMZHQ8CHK
>          mGLhcYxZy5JunU52QisXt4FFyfQ0o3k1GLpV3nZ9ThM4q9zrbJzeSipHDGa6FPQJh62n
>          v3kVEvWZWPg7dLlLPt7JEkOzdmVmyCaPSoni04+pbJmhw87rjbe2dT7fm2nPPCD+WEWI
>          wBlU0CcAcesTS00QNF+OmM7f5wdXks/QdylDH18AzfMTga6tvM/xNOtyXwOuijGK8Kr3
>          phlxwDZe288uGF1WJ7RGjE9fxZFo8lR0eMthRNQLOWG7KcPifiCrc1hPyFiBXx6gf6Cq
>          MiFQ==
> X-Gm-Message-State: AElRT7FYE1OzAgoe17hZykh3hgJnGrKzL3xa/UrBlpJXSNaDmfETd5lL
> 	NQBlZ+J1INnCpeNRzJZ1nTuorGNByWQmnpOWUtc=
> X-Google-Smtp-Source: AG47ELvNJkx/kNTVjQ3HJ20YPFVK0Tvc80qrQIXAkJ04tZNrFX61nAUV/+O4B/UJk+eunVjiJzNYwwG+CckujxXt2uw=
> X-Received: by 10.55.9.135 with SMTP id 129mr19301797qkj.221.1520231235120;
>  Sun, 04 Mar 2018 22:27:15 -0800 (PST)
> MIME-Version: 1.0
> Received: by 10.140.91.42 with HTTP; Sun, 4 Mar 2018 22:27:14 -0800 (PST)
> From: Ryan vAN GINNEKEN <ryan.computerking@gmail.com>
> Date: Sun, 4 Mar 2018 23:27:14 -0700
> Message-ID: <CAP8qfP252L03YyAAroDoZUaZbhpz_BE+SpANZOF8n7sZHmqdMg@mail.gmail.com>
> Subject: test support 1000000 times
> To: support@reddhart.ca
> Content-Type: multipart/alternative; boundary="001a11487b8cbef25b0566a46aee"
> 
> --001a11487b8cbef25b0566a46aee
> Content-Type: text/plain; charset="UTF-8"
> 
> port 25 not alias
> 
> --001a11487b8cbef25b0566a46aee
> Content-Type: text/html; charset="UTF-8"
> 
> <div dir="ltr">port 25 not alias<br></div>
> 
> --001a11487b8cbef25b0566a46aee--

**Comment by erost** [comment]
Unfortunately that’s the “correct” behaviour, at least right now. Implementing something generic for dealing with emails was never easy, so we resort to scan all headers for the desired destination address.

That works in some cases:
- one inbox exposed as public address
- one internal inbox with multiple exposed aliases
But doesn’t work in a specific case:
- one publicly exposed inbox with multiple aliases
and that is unfortunately your case here. 

The solution here would be to create something like internal-support@projectA.com, and then add support@projectA.com and support@projectB.com

Does that fit your setup? 
In any case, the documentation needs to be updated to highlight the limitation mentioned above

**Comment by c0mputerking** [comment]
Hello again all, and first off thank you very much for including such a great feature, really useful, email tickets is one of the main reasons i started using Lavagna.  Even if i have to create an email account for each project it would NOT be a deal breaker or showstopper for me, but i am still unclear about that requirement, and have summarized with another example below. 

Ok so I am still a bit unclear about your suggested implementation ... If I create one real email address of internal-support@projectA.com and then 2 alias for support@projectA.com and support@projectB.com ... that would work for adding tasks to 2 different Projects? If so that is perfect for me.

If not, i'm still very happy with email ticket support and will just go ahead and create an full email account for each project.
