### ISSUE TITLE
Forbidden when trying to access setup page in installation 

### ISSUE THREAD

**Issue by irfanr** [digitalfondue/lavagna#102]
Hi,

I have problems accessing setup page (http://localhost:8080/setup/) that said:

> Problem accessing /setup/. Reason:
> 
>     Forbidden

I'm using standalone app (jetty) using dev mode with hsqldb memory.

Is there any workaround for this? Great thanks for the help :)

**Comment by syjer** [comment]
hi @irfanr , if you are using it in dev mode with hsqldb, then it's already configured with some sample data, so the setup application is disabled.

you can pass the parameter -spring.profiles.active=prod to enable the setup option.

**Comment by irfanr** [comment]
I worked with prod mode. Thanks!
