### ISSUE TITLE
New User cannot drag and drop?

### ISSUE THREAD

**Issue by c0mputerking** [digitalfondue/lavagna#105]
Just trying to get some users and permissions setup, and as stated in the the Lavagna Documentation I have created a Global Role (I called it General) and gave it only the permission directly below.  I then added my new user and plan to add all new users to that Role as per the Documentation 

Update User Profile
Search

I then create another Project Role with full permissions ie I checked everything and added my new user to that Project Role things work mostly as expected.  However the new user cannot drag and drop cards from one column to another, I tested and the user can move cards from one column to the other using the three dots menu without issue.

**Comment by syjer** [comment]
hi @c0mputerking , I'll have a look.

**Comment by syjer** [comment]
@c0mputerking , found the bug, we didn't passed the project in this specific case :).

I'll do a new stable release with this fix.

**Comment by syjer** [comment]
@c0mputerking the release 1.1.1 has been published with this fix too: https://github.com/digitalfondue/lavagna/releases/tag/lavagna-1.1.1 .

**Comment by c0mputerking** [comment]
Thank you VERY much :)
