### ISSUE TITLE
Download export

### ISSUE THREAD

**Issue by SlytherinCz** [digitalfondue/lavagna#107]
Clicking Download Export results in following stack trace
```
NS_ERROR_MALFORMED_URI:  blank:1
    <anonymous> about:blank:1:1
    AdminExportImportController/ctrl.doExport http://localhost:8080/resource/app-1.1.js:6562:13
    fn http://localhost:8080/resource/app-1.1.js line 284 > Function:4:175
    e http://localhost:8080/resource/app-1.1.js:329:346
    $eval http://localhost:8080/resource/app-1.1.js:192:351
    $apply http://localhost:8080/resource/app-1.1.js:193:55
    compile/</< http://localhost:8080/resource/app-1.1.js:329:396
    jg http://localhost:8080/resource/app-1.1.js:81:477
    d http://localhost:8080/resource/app-1.1.js:81:426
```
Using image `digitalfondue/lavagna:stable` as of today.

Firefox Quantum 61.0.1 (64-bit)

**Comment by syjer** [comment]
Hi @SlytherinCz , I'll have a look :)

**Comment by SitoCH** [comment]
I pushed a fix in both branches, this is a really strange issue that affected only Firefox...
Waiting for @syjer to publish a new release so we can update the Docker images.

**Comment by syjer** [comment]
should be done. Will need some time for uploading.

**Comment by SitoCH** [comment]
Docker images updated, the export is now fixed for Firefox.
