### ISSUE TITLE
RESTful API?

### ISSUE THREAD

**Issue by NextDesign1** [digitalfondue/lavagna#109]
Hi there,

Is a RESTful API in the works? Being able to control lavagna from other applications would be a great addition.

Thanks.

**Comment by syjer** [comment]
Hi @NextDesign1 , what kind of API would you need? 

As technically we already have an undocumented REST api for the angular application that we could expose/cleanup.

**Comment by shashaanktulsyan** [comment]
something similar to net.rcarz.jiraclient.JiraClient
