### ISSUE TITLE
Way to set project specific permissions?

### ISSUE THREAD

**Issue by 0ptimus** [digitalfondue/lavagna#11]
Just started playing with Lavagna and using LDAP authentication (nice!).  Is there any way to set project specific permissions to users?  For example I have a project ("project1"), I want user1 to be an "project administrator" just on a project1 and be able to add/update/delete anything for a project.  And for user2, just have read/add/update but no delete.  And another user3, would only have read only to review the project/tasks.  Is this possible?  By the way if there were multiple projects, the users would only have access to the project s/he is given permissions to.  Is this possible in Lavagna?

Looks nice so far.

**Comment by erost** [comment]
Hi 0ptimus, 
yes that's definitely possible.
How to do it:
1. a general Administrator user should setup the project first and then, in the project settings, create a role that works as a project administrator and add user1 to it. At this point, user1 can configure anything related to your project.
2. user1 can then create additional roles with the permissions you need for user2 and user3, and add those users to their desidered roles.

You can look here:
http://help.lavagna.io/03-configuration-and-administration/03-05-roles-and-permissions.html
and here:
http://help.lavagna.io/04-user-manual/04-07-project-admin.html#project-administration
for additional details.

Let me know if you need further help.
Eros

**Comment by syjer** [comment]
Adding over what @erost  said, on the global role level, you can create a simple "BASIC" role with the following permission:
 - UPDATE_PROFILE
 - SEARCH

And assign the users that need a restricted access.

Then in each project, you create the various roles with the necessary permissions.

**Comment by 0ptimus** [comment]
Thanks @erost and @syjer !  Will take a look and try out those tips.

**Comment by SitoCH** [comment]
I'm closing this issue since it appears to be resolved.
