### ISSUE TITLE
csrf token not equal to expected, while confirm and submit User

### ISSUE THREAD

**Issue by Bertinmendonsa** [digitalfondue/lavagna#113]
![screenshot from 2018-11-24 10-56-12](https://user-images.githubusercontent.com/25399465/48964914-4d150e00-efd8-11e8-956a-a4dbafbed9f0.png)

Getting this error by clicking on the **activate** button, values are not getting saved in to database.

**Comment by syjer** [comment]
hi @Bertinmendonsa , I'll have a look, thank you for the report.

**Comment by syjer** [comment]
@Bertinmendonsa , I'm trying to reproduce the error, it seems to be a timing/session issue, as I'm not able to reproduce it easily (at the moment 1 out of 10~). If you do a reload of the page and you redo the setup, does it work?

**Comment by Bertinmendonsa** [comment]
Hi,

I tried to reload the page and redo the setup, No it did't  work for me.

when I click that activate button, I am getting the error

Thank you for the support.

**Comment by syjer** [comment]
hi @Bertinmendonsa , could you try to use https://oss.sonatype.org/content/repositories/snapshots/io/lavagna/lavagna/1.1.3-SNAPSHOT/lavagna-1.1.3-20181124.140151-1-distribution.zip ? I've updated/changed some code, it may help you. Thank you.

**Comment by SitoCH** [comment]
Closed due to inactivity
