### ISSUE TITLE
Multicore support/Is Lavagna only singlethreaded?

### ISSUE THREAD

**Issue by corbet-consulting** [digitalfondue/lavagna#118]
Hi @syjer,

I have noticed some lags when using Lavagna. I am not sure why ... so I digged system utilization using top (Linux) and found out that most of the server's resources remain unused. I am running an Octacore ARM (!) processor, yet I often saw only 10-12% utilization while there is plenty of free RAM. I can also assume storage IO is not the bottleneck (Samsung 860 EVO SSD).

I am not sure whether this implies that Lavagna is singlethreaded, so I might as well post this as a ticket, so you can close it and handle all future requests.

If however Lavagna is singlethreaded I would really like to receive recommendations about the performance of the setup (What CPU should one use for which amount of users/what kind of usage?).

**Comment by syjer** [comment]
hi @corbet-consulting , I can confirm that Lavagna is multi threaded.

But as most java applications, you still need a "beefy" cpu, additionally, the jvm as far as I know, it's not really optimized for ARM. (You should check if it even has the JIT compiler enabled).

**Comment by corbet-consulting** [comment]
Thanks for your answers. They are really helpful. 

How can one check whether "the JIT compiler is enabled"? I guess a lot of people run software on ARM these days, so it might be helpful to more people than myself to know :)

**Comment by syjer** [comment]
hi @corbet-consulting , unfortunately I'm not sure how you can check. In theory, if you have a recent jvm (java 9+) you can be sure that the JIT should be present.

If you write in the console: `java -version` what's your output?

**Comment by SitoCH** [comment]
Usually on ARM the JIT is disabled, that's why on our test Docker image for Raspberry we use the Zulu JVM:

https://github.com/digitalfondue/lavagna-docker/blob/raspberry-pi/Dockerfile

**Comment by corbet-consulting** [comment]
Thank you for your comment. I have now installed Zulu JVM and indeed I see much higher performance which resolves my performance problem. It might be a good idea to add some information on your install page so newcomers can more easily find this information :)

**Comment by SitoCH** [comment]
Glad to help you, it's really strange that in 2019 the JIT is still disabled and we have to switch to another JVM...
