### ISSUE TITLE
full-text search

### ISSUE THREAD

**Issue by corbet-consulting** [digitalfondue/lavagna#119]
Hi,

I am facing another issue which most likely will turn out to be a configuration problem most likely by myself.

Lavagna.io highlights "Power search: metadata and full-text search are available." as feature of the software. Having created a board and currently having xy cards we tried out full-text-search but found out that we do not get the expected results: Only the label is ever queried. Not the full issue-description.

I am using Zulu JVM (thanks again), PostgreSQL and Lavagna. What information would be helpful to find the cause of this behaviour?

Because I know that the internal DB does not support searching, I installed Postgres and use it with the lavagna table created during setup. There are no apparent error messages regarding db usage. Postgres runs on the server. ... So yeah, any log or config I can scrutinize (and post) would be a helpful answer :)

**Comment by syjer** [comment]
hi @corbet-consulting , could you provide a screenshot of your query? In theory you don't need to do anything special.

**Comment by SitoCH** [comment]
Closed due to inactivity
