### ISSUE TITLE
JS looping errors after successful login

### ISSUE THREAD

**Issue by armstrhb** [digitalfondue/lavagna#12]
Hello Lavagna team,

We've set up Lavagna 1.0.0 (also tried with the new 1.0.1 published today) within Tomcat8.  Went through set up successfully, but after login, the javascript console logs are spammed with the following error (as if through loop):

    app.js:1452 Uncaught Error: [$rootScope:infdig] http://errors.angularjs.org/1.2.28/$rootScope/infdig?p0=10&p1=%5B%5B%22fn%3…  D!1%3Breturn%20n%7D%3B%20newVal%3A%2030041%3B%20oldVal%3A%2030040%22%5D%5D(anonymous function) @ app.js:1452$get.h.$digest @ app.js:1557(anonymous function) @ app.js:1559e @ app.js:1483(anonymous function) @ app.js:1487
    app.js:1538 Error: Failed to execute 'pushState' on 'History': A history state object with URL 'http:' cannot be created in a document with origin 'http://techutilities.bcbssc.com'.
        at Error (native)
        at se.h.url (http://techutilities.bcbssc.com/lavagna/resource/app.js:1485:275)
        at http://techutilities.bcbssc.com/lavagna/resource/app.js:1537:48
        at h.$get.h.$eval (http://techutilities.bcbssc.com/lavagna/resource/app.js:1559:32)
        at h.$get.h.$digest (http://techutilities.bcbssc.com/lavagna/resource/app.js:1556:117)
        at http://techutilities.bcbssc.com/lavagna/resource/app.js:1559:143
        at e (http://techutilities.bcbssc.com/lavagna/resource/app.js:1483:497)
        at http://techutilities.bcbssc.com/lavagna/resource/app.js:1487:235(anonymous function) @ app.js:1538$get @ app.js:1514$get.h.$digest @ app.js:1556(anonymous function) @ app.js:1559e @ app.js:1483(anonymous function) @ app.js:1487

I followed http://help.lavagna.io/ to setup the environment, and accepted the proposed URL for the base URL.  Some googling ([link](http://stackoverflow.com/questions/20079704/javascript-history-pushstate-not-working)) ([link](https://github.com/angular/router/issues/326)) suggests that this is angular shutting down the history push, thinking it's cross domain; however the base URL chosen is accurate to the requests coming in for our local installation: http://techutilities.bcbssc.com/lavagna

The link that I'm redirected to after login is: http://techutilities.bcbssc.com/lavagna/, here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/11358169/9283426/d3b41650-42a1-11e5-8fbe-c0c2e77536d7.png)

Looks like something from a URL resources map isn't quick linking correctly.

**Comment by syjer** [comment]
@armstrhb 

Thanks for the report, I'll try to fix the issue ASAP.

**Comment by syjer** [comment]
@armstrhb Ok, I'm able to reproduce the bug locally, sorry about not testing the application on tomcat 8 :(. I'll do a fix and a release.

**Comment by syjer** [comment]
(the issue is present on tomcat7 too)

**Comment by syjer** [comment]
Ok, the issue was caused by the fact that tomcat was serving the unprocessed template directly, bypassing the controller that was processing the root directory of the application.

@armstrhb  Thanks for the opening this issue. I'll do a 1.0.2 release.

**Comment by syjer** [comment]
@armstrhb could you try the release 1.0.2: https://repo1.maven.org/maven2/io/lavagna/lavagna/1.0.2/lavagna-1.0.2-distribution.zip  ?

**Comment by armstrhb** [comment]
@syjer thanks for the quick turnaround, issue is corrected. Thanks again!

**Comment by syjer** [comment]
@armstrhb Thanks for the bug report :).
