### ISSUE TITLE
problem trying building the lavanga

### ISSUE THREAD

**Issue by ofiramit** [digitalfondue/lavagna#122]
hi.
i got those errors when i try to build lavanga with maven.

"Some problems were encountered while building the effective model for io.lavagna:lavagna:war:1.1.3-SNAPSHOT "
"'parent.relativePath' of POM io.lavagna:lavagna:1.1.3-SNAPSHOT (/pom.xml) points at io.lavagna:lavagna instead of org.sonatype.oss:oss-parent, please verify your project structure @ line 4, column 13"

"The project io.lavagna:lavagna:war:1.1.3-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html"

**Comment by syjer** [comment]
hi @ofiramit , which version of maven are you using?

**Comment by ofiramit** [comment]
hi.
i used maven 3.6-jdk-8

**Comment by syjer** [comment]
@ofiramit , ok, I guess that's the main issue. I'll try to update it on my side and check what is wrong.

**Comment by ofiramit** [comment]
hi.
maybe you have a recommend maven imgae to use?

thx

**Comment by syjer** [comment]
Hi @ofiramit , I did a test with maven 3.6.2, the build work correctly.

I got the warning:

```
[WARNING] The project io.lavagna:lavagna:war:1.1.3-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
```

Which I will fix later.

But the build worked as expected:

```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  55.179 s
[INFO] Finished at: 2019-09-09T00:00:22+02:00
[INFO] ------------------------------------------------------------------------
```

Tested with:

```
mvn -version
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)
Maven home: /home/xyz/programs/apache-maven-3.6.2
Java version: 1.8.0_222, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.fc30.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.2.11-200.fc30.x86_64", arch: "amd64", family: "unix"
```

For the various warning, I'll try to fix them later.

**Comment by syjer** [comment]
@ofiramit , I've removed the problematic entry in the pom.xml, now it build without that warning with the latest version of maven.

**Comment by SitoCH** [comment]
Closed due to inactivity
