### ISSUE TITLE
BASE_APPLICATION_URL   ignores  subfolder

### ISSUE THREAD

**Issue by akhepcat** [digitalfondue/lavagna#125]
when setting up a reverse apache proxy on  (https://MYDOMAIN.DOM/lavagna/  to point to the localhost:8081  instance,  lavanga ignores the  directory part of the URI.

Even forcing the first access into the setup screen and setting the baseurl  correctly, after applying it is still redirecting to the '/'  instead of  '/lavagna'

**Comment by akhepcat** [comment]
There are multiple instances in the code that look like:
`url: '/search/?q&page',`
which completely ignores the baseurl directive, and anchors the url incorrectly.

**Comment by SitoCH** [comment]
Hi,
from what I remember it should work but we don't test that configuration. I read that you're using a reverse proxy, can you configure it to https://lavagna.MYDOMAIN.DOM ? This is our standard solution and it works fine.

**Comment by akhepcat** [comment]
I don't have the ability to add subdomains, which is why i added it as a reverse via directory re-write.

A clean-up of all the URLs, so that they follow the baseurl directive, solves the issue moving forward, and keeps testing in the future much cleaner, as things will always behave as expected.
