### ISSUE TITLE
Run first time on Public IP?

### ISSUE THREAD

**Issue by arjitc** [digitalfondue/lavagna#13]
Hello,
Lavagna defaults / redirects to localhost:8080/ right after I input my public_ip:8080, is there anyway to hardset the IP address during launch?

**Comment by syjer** [comment]
Hi @arjitc , 

The address is stored in the table LA_CONF with the key BASE_APPLICATION_URL , you can modify it with your preferred sql client :).

**Comment by arjitc** [comment]
Ah any way to set this under the dev option? / quick use option? But yes, I'll give it a try with a mysql backend, screenshots look like what I just need :+1:

**Comment by syjer** [comment]
Unfortunately not at the moment. For the next version we will remove the need of this variable in the login process, thanks for opening the bug :). It's a nice reminder :D

**Comment by arjitc** [comment]
ah okay, I'll give the standard/production setup a try later today :+1:

**Comment by syjer** [comment]
FYI, this issue has been fixed in the master. So it will be present in the 1.1 and 1.0.3 release.
