### ISSUE TITLE
How can I move projects to the trashcan

### ISSUE THREAD

**Issue by nickbe** [digitalfondue/lavagna#133]
... and empty the trash to delete projects and old cards for good?

**Comment by syjer** [comment]
hi @nickbe , at the moment you can only archive projects.

Additionally, deleting for good a card or projects is not supported as it has some not simple to handle implications (for example: linked issues).

I don't think we will ever support the total deletion of cards and projects.

**Comment by nickbe** [comment]
I think that this implies privacy issues. A user should be able to delete his own comments and also delete his own cards if he wants to. Otherwise we're bound to have a lot of trash accumulating over time.
