### ISSUE TITLE
Compiling with current JDK throws error

### ISSUE THREAD

**Issue by nickbe** [digitalfondue/lavagna#134]
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (java-compile) on project lavagna: Compilation failure
[ERROR] X:\Workspace\GitHub-Systeme\lavagna\src\main\java\io\lavagna\service\ProjectService.java:[37,8] cannot access java.lang.Object
[ERROR]   bad class file: /modules/java.base/java/lang/Object.class
[ERROR]     class file has wrong version 58.0, should be 53.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.

So the question is exactly which JDK version was used to compile the project?

**Comment by syjer** [comment]
hi @nickbe , 

using sdkman, I'm using the following version:
> $ sdk list java
...
>8.0.242      | open    | installed  | 8.0.242-open

**Comment by nickbe** [comment]
Seems that this version for windows is not available for download anymore.

**Comment by syjer** [comment]
@nickbe , you can download from: 

 - https://adoptopenjdk.net/releases.html
 - https://developers.redhat.com/products/openjdk/download
 - https://www.azul.com/downloads/zulu-community/?architecture=x86-64-bit&package=jdk-fx

**Comment by nickbe** [comment]
Success 😁  Thanks a lot !
