### ISSUE TITLE
Bug: File upload 0B

### ISSUE THREAD

**Issue by majugurci** [digitalfondue/lavagna#136]
Hi,

I have found this previous issue: https://github.com/digitalfondue/lavagna/issues/92

I believe this bug is still present.

If I add any file while while creating the card the file becomes 0B.
If I add the file to previously created card it is working fine.

Once the file becomes 0B I need to rename it and change it's content in order to get it to work.

**Comment by syjer** [comment]
hi @majugurci  I'll have a look, thank you for opening the bug.

**Comment by majugurci** [comment]
Thank you for this wonderful app :)

Here is a suggestion: if it is too much work to investigate/fix this bug maybe it's easier to just disable the file upload when inserting the card and enable it when updating the card.

**Comment by syjer** [comment]
@majugurci I think I have pinpointed and fixed the issue, I'll do a release asap :)

**Comment by syjer** [comment]
@majugurci , I did the release 1.1.6 (https://github.com/digitalfondue/lavagna/releases/tag/lavagna-1.1.6) , the docker image will be done asap (if you are using it)

**Comment by majugurci** [comment]
@syjer Thank you very much for fast work. I have tested the new version and it is working all right :)

**Comment by syjer** [comment]
@majugurci thank you for opening the issue and testing :+1: :)
