### ISSUE TITLE
Procedure for lavagna in eclipse 

### ISSUE THREAD

**Issue by Ghosty001-lester** [digitalfondue/lavagna#139]
Hello help me out with the entire procedure on how to configure and run lavagna in eclipse. Thank you.

**Comment by syjer** [comment]
hi @Ghosty001-lester , as I don't use eclipse, I can't really help you. I would guess that you need to install both the lombok and kotlin plugin.

**Comment by Ghosty001-lester** [comment]
What about in Intellij? Do you have the procedure?

**Comment by syjer** [comment]
@Ghosty001-lester , well, you import the project as a gradle one,  install the lombok plugin (https://plugins.jetbrains.com/plugin/6317-lombok) and you should be good to go.

**Comment by Ghosty001-lester** [comment]
What about running?
How am I supposed to run it. I mean should I run lavagna from the Intellij
or from a web?

**Comment by syjer** [comment]
@Ghosty001-lester it's written in the README: https://github.com/digitalfondue/lavagna#execute .

**Comment by Ghosty001-lester** [comment]
when i try this mvn jetty:run
I get this error  cannot access java.util.List
[ERROR]   bad class file: /modules/java.base/java/util/List.class
[ERROR]     class file has wrong version 55.0, should be 53.0
[ERROR]     Please remove or make sure it appears in the correct
subdirectory of the classpath.

what should I do?

**Comment by syjer** [comment]
hi @Ghosty001-lester , as written in the [readme](https://github.com/digitalfondue/lavagna#java-and-kotlin), you should use java 8 to run it.

**Comment by syjer** [comment]
I would advise to use https://sdkman.io/ for handling the various jvm versions
