### ISSUE TITLE
Card description change does not update "last updated by" user

### ISSUE THREAD

**Issue by fredtj** [digitalfondue/lavagna#142]
jane creates a card with a description
bob edits the description

card shows: " Updated 1 time - Last Updated By: jane on Sep 23, 2020 2:06 PM "

**Comment by fredtj** [comment]
looks like it just isn't updated immediately, but if you close and re-open the card, it is correct.

**Comment by syjer** [comment]
hi @fredtj , you are right, we were not reacting to the change of the "userId". I've pushed the fix.

Thank you for opening the bug :+1:
