### ISSUE TITLE
Graceful way of terminating lavagna

### ISSUE THREAD

**Issue by ahmedmohiduet** [digitalfondue/lavagna#143]
Can I terminate Lavagna process from my terminal gracefully? Can't find any documentation shutting Lavagna down gracefully.

**Comment by syjer** [comment]
hi @ahmedmohiduet , 

>Can I terminate Lavagna process from my terminal gracefully

yes, you can terminate the process without issues. In the end the application state is stored in the database.

**Comment by ahmedmohiduet** [comment]
hi @syjer : so, can I issue some non-CTRL+C / non-KILL command which would have Lavagna exit? I am using hsqldb file mode. but leaving Lavagna parent process terminated leaves my hsqldb db properties file property "modified=yes". And my command line backup command failing. I am looking more of a command line automated backup from my file-mode hsqldb

**Comment by ahmedmohiduet** [comment]
Closing. It looks like exists inside hsqldb server mode...
