### ISSUE TITLE
 Consider the existence of 'unnaccent' extension on database for Postgresql

### ISSUE THREAD

**Issue by alinuxGit** [digitalfondue/lavagna#146]
In some context for security reasons the database user could not have superuser or database owner privileges for creating the **_unaccent extension_**. This extension could be create by database admin, but at first installation the next error will be thrown:

``` shell
Caused by: org.postgresql.util.PSQLException: ERROR: extension "unaccent" already exists
```
I think will be enough to modify the next sql statement on file **V1__INITIAL_VERSION.sql**

``` sql
create extension if not exists unaccent;
```

**Comment by syjer** [comment]
hi @alinuxGit , thank you for opening the issue, I'll have a look if I can modify the statement as you suggested.

**Comment by syjer** [comment]
I've pushed the fix. After I do some updates, I will do a release. Thank you for opening the issue :)

**Comment by alinuxGit** [comment]
thank you @syjer I really appreciate your fix velocity. I can't wait to install the new version.
