### ISSUE TITLE
Icons not shown.

### ISSUE THREAD

**Issue by smvarela** [digitalfondue/lavagna#16]
In Fedora Linux 22 (64 bits) with Lavagna 1.0.2, the icons are not shown correctly. The problem occurs in Chrome 46, but in the same machine with Firefox the icons are shown without problem. 
Attached two images to show the difference.

![lavagna-chrome](https://cloud.githubusercontent.com/assets/10855160/9429894/1263fede-49e0-11e5-8847-f0d3d907082b.jpg)
![lavagna-firefox](https://cloud.githubusercontent.com/assets/10855160/9429895/126bc0b0-49e0-11e5-8be9-31d987e7e598.jpg)

**Comment by syjer** [comment]
Hi @smvarela , it seems that you have the same issue as reported in https://github.com/digitalfondue/lavagna-docker/issues/1 .

If the browser does not send the cookie it's most likely the same issue (that will be fixed when you will receive the update to chrome)

**Comment by smvarela** [comment]
Hi, you are right, seems to be the same issue. The cookies are not send by the browser, but the problem now is fixed by Chrome.  https://codereview.chromium.org/1267023004

**Comment by smvarela** [comment]
Hi, with Chrome  46.0.2490.4 dev (64-bit) all icons are correctly rendered.

**Comment by syjer** [comment]
Thank you for the confirmation :D
