### ISSUE TITLE
GitHub OAuth is not working

### ISSUE THREAD

**Issue by spiralw** [digitalfondue/lavagna#162]
Hi, I tried to set up OAuth with GitHub and I am getting the following error after getting redirected from GitHub:

> **Username/Password is not correct or the account is not enabled**

I tried creating the account manually from admin panel with the `oauth.github` provider and marking it as active, but the error is still present.

Here is the configuration in Lavagna:
![image](https://user-images.githubusercontent.com/64013111/147652468-c02b486b-ae1c-4b22-a615-9b25f4c22c6c.png)

Here is the configuration in GitHub:
![image](https://user-images.githubusercontent.com/64013111/147652548-95bee5cc-16f0-4ac6-8106-1a642f5e446e.png)

What am I doing wrong?

**Comment by syjer** [comment]
hi @spiralw 

looking at the configuration it seems everything is correct, I'll have a look this afternoon if we have introduced some bug.

**Comment by syjer** [comment]
hi @spiralw , I confirm we need to change something on our side, we need to update our oauth connector: https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/
.

**Comment by syjer** [comment]
I'll do a small check for the other oauth provider, if everything is ok, I'll do a release tomorrow, thank you for reporting the issue :+1:

**Comment by syjer** [comment]
should be fixed in the 1.1.9 release.

**Comment by spiralw** [comment]
it's working perfectly now, thanks!
