### ISSUE TITLE
Github login bad url

### ISSUE THREAD

**Issue by erm3nda** [digitalfondue/lavagna#21]
I've tried to enable Github login using my API key, but oauth url is not okey.
Got 404 from github.

**Comment by syjer** [comment]
Hi @erm3nda , I'll check on our test instance.

**Comment by syjer** [comment]
Hi @erm3nda ,it  work correctly on out test instance. You should check that the urls/token/users are correct.

For example in our test instance we have:

**github configuration:**

![github_app_conf](https://cloud.githubusercontent.com/assets/498146/12221705/853237f8-b7a6-11e5-8a66-fd7dc2ae6a6b.png)


**lavagna oauth configuration:**

![oauth_github](https://cloud.githubusercontent.com/assets/498146/12221707/95186a52-b7a6-11e5-8cfa-072c9eacef47.png)

The "client id" from github must be put in the "api key" section and the "client secret" in the secret section. The callback url provided by lavagna should be pasted in the github configuration.

And finally, the user must be present in the system  with the oauth.github provider.

**Comment by erm3nda** [comment]
Ok, was my mistake, did not pay good attention.
Thank you.

**Comment by syjer** [comment]
you're welcome :).
