### ISSUE TITLE
[Feature Request] Calendar View and simplicity features

### ISSUE THREAD

**Issue by dotkiddo** [digitalfondue/lavagna#22]
Dear Lavagna Development Team,

I would like to make the following requests/suggestions for future features:

- a "calendar view" for viewing upcoming and missed/met deadlines on tasks/cards.
- a way to add tasks and due dates directly from the board view, rather than having to go into the card detailed view.
- multiple selection of cards for adding labels, due dates and/or tasks (once again, directly from the board view) to many cards simultaneously
- keyboard shortcuts, both for navigational purposes and easier editing

On the other hand, I also want to say thank you sooo very much for all the effort that has gone into the project thus far, I would love to contribute in any way possible, this has so far been an incredibly useful application and I can only see it becoming more so. Could you tell me how I could make a meaningful contribution? (Code-wise)

Thank you!!
dotKiddo

**Comment by syjer** [comment]
Hi @dotkiddo ,

Thank you for using Lavagna :D.

- For the calendar view, yes, it's something that we will do in a future release (1.2 most likely).
- For the keyboard shortcuts, agree. we will try to integrate them in the 1.1 release (or event 1.0.x).

About the multiple selection of cards and setting the due dates directly from the board: you can already do that :) (it's a little bit hidden - we are trying to improve the discoverability of the app too in the 1.1 release).

The "Bulk operations" mode is what you want: http://help.lavagna.io/04-user-manual/04-03-board/04-03-05-bulk-operations.html . After you have clicked the "empty checkbox" icon, you are able to select multiple cards and do the following actions directly from the board:

- Assign to: assign the selected card(s) to the selected user. Use the input field to search for a user by name
- Remove assign: remove the selected card(s) from the selected user tasks list
- Reassign to: remove all the currently assigned users, and assign the card(s) to the selected user
- Set due date: set, or update, the deadline date on the selected card(s)
- Remove due date: remove the deadline date on the selected card(s)
- Set/Update milestone: set, or update, the milestone on the selected card(s)
- Remove milestone: remove the selected card(s) from their current milestone, and set them back in the Unassigned milestone
- Add label: set a common label on the selected card(s); the input fields depend on the label type
- Remove label: remove the selected label from the selected card(s)
- Move to archive: archive the selected card(s)
- Move to backlog: move the selected card(s) to the board backlog
- Move to trash: move the selected card(s) to the board trash bin

Adding new tasks it's something that is currently missing, but we will add it!

**Comment by dotkiddo** [comment]
Thank you for the incredibly quick response!

I can't wait to see what you guys do :smiley:
