### ISSUE TITLE
Is MariaDB supported ?

### ISSUE THREAD

**Issue by likeitneverwentaway** [digitalfondue/lavagna#26]
Hi, I'm using MariaDB and I can't get Lavagna to work. The log is quite huge so I don't expect you to read it but [here it is](https://gist.github.com/likeitneverwentaway/3812155a9339083788d4055ececbad29) :)

This is very new to me, but I see that it's trying to use mysql connector, as MariaDB is a fork is it working ? Do I need to install MDB connector or everything is lost ? 

Thank you

**Comment by syjer** [comment]
Hi @likeitneverwentaway , we didn't tested with mariadb, so it's possible that you could have some issues.

We will add mariadb in the continous integration, thanks for the reminder!

From the log, the error is quite simple:

`
Access denied for user 'user'@'localhost'
`

The db configuration is most likely not correct: you should ensure that username, host, port and password are correct.

**Comment by likeitneverwentaway** [comment]
> We will add mariadb in the continous integration, thanks for the reminder!

That's awesome to hear thank you ! And you were right I my login informations were incorrect... Although now I still can't get it to work, [new log](https://gist.github.com/likeitneverwentaway/7dbdbd792b1fb89085ba2ea45f475dba). My server runs Nginx, I don't have Apache, could that be a problem?

Thanks again for your answer!

**Comment by syjer** [comment]
@likeitneverwentaway what you use as a reverse proxy is not a concern for lavagna :).

Now from the log:

` Schema `lavagna` contains a failed migration to version 1 !`

it seems that the database/schema  creation has failed, could you try to drop and recreate the database "lavagna"?

If it does not work, it means that we have some incompatibilities with mariadb :( that I'll try to track down.

Which version of mariadb are you using?

**Comment by likeitneverwentaway** [comment]
`Server version: 10.0.25-MariaDB-0+deb8u1 (Raspbian)`
 I dropped the database and used the command from the docs to recreate it, still get a 503 service unavailable, log. It seems to be a problem with the database as you said, are `information_schema `and `performance_schema` lavagna's ? Should I drop them too ?

**Comment by syjer** [comment]
from the log :

`Thread stack overrun:  5920 bytes used of a 131072 byte stack`

it seems that the mariadb is configured for a small device, maybe you can try to increase the thread stack size. In your mariadb configuration file (my.cnf?) you should comment out the line that set the thread stack:

from:
`thread_stack		= 128K`

to
`#thread_stack		= 128K`

If you try to comment it and re-create the db maybe this time lavagna will be able to create correctly the tables.

(about `information_schema` and `performance_schema`, no, they are internal table, you should not remove them).

**Comment by likeitneverwentaway** [comment]
You're awesome!! I'm pretty sure that did, now it redirect me to /setup (which is a 404 because of my nginx mess) but that should do it!

Is there any other way to access the setup ? I have a very strict niginx environment (I'm using Yunohost if you know of it) so the redirection is not working... Anyway I'll figure this out, I think Lavagna is working ok with MariaDB :)

**Comment by syjer** [comment]
Thank you :) 

If you have any questions, feel free to open new issues :)

**Comment by SitoCH** [comment]
As a sidenote I added MariaDB to the CI so we can continue to check the compatibility in the future releases.
