### ISSUE TITLE
HTTP ERROR 403 on page refresh

### ISSUE THREAD

**Issue by leader80** [digitalfondue/lavagna#3]
Hi Lavagna crew,
if you are in the settings section under Roles edit and you press refresh (ctrl+R or F5) it throws an error 403 and you need to go back to dashboard to make the application work again.

Cheers
L

**Comment by syjer** [comment]
Most likely related to #1 and #3 (because there is a permission check) . The fix that I've did for #1 seems uncomplete.

**Comment by syjer** [comment]
should be fixed and deployed on openshift, thanks for the report :D

**Comment by leader80** [comment]
I see a strange error message at the bottom of the window during refresh
![error2](https://cloud.githubusercontent.com/assets/73665/6963365/c7b3fc98-d93e-11e4-97aa-c6cfcef40f12.png)

**Comment by syjer** [comment]
This message is shown when the websocket connection is closed (which happen when the page is refreshed/closed).

I'm wondering if we are able to detect the refresh event and suppress the message.

**Comment by leader80** [comment]
couldn't you just suppress the refresh event? 
Anyway it is possible to detect it.

**Comment by syjer** [comment]
Well, for sure listening to the window.close event can be a good entry point. I'm hoping that it's enough.

Or maybe listening to the $destroy event from the attached $rootScope from angular.

**Comment by leader80** [comment]
I did something like that in the past:
$rootScope.$on('$routeChangeStart', function())
And then check if it is the same page.

-> not really sure if it is the best way :(

**Comment by syjer** [comment]
$window.addEventListener("beforeunload",function() {ignoreErrorOnApplicationDestroy = true;});

Seems to work :)

**Comment by syjer** [comment]
deployed on openshift
