### ISSUE TITLE
[Feature Request] - E-mail to Card

### ISSUE THREAD

**Issue by fernandodiacenco** [digitalfondue/lavagna#32]
I would love to see something like this on Lavagna:

You create an email and several aliases to this email, for example:

Email: tasks@company
Aliases: sales@company, marketing@company, support@company

And when an email is sent to one alias, Lavagna automatically creates a card in the configured board, for example sending and email to marketing@company creates a card on the "Marketing" board

Thanks for the attention.

**Comment by syjer** [comment]
Hi @fernandodiacenco , good idea :)

We will try to implement something :)

**Comment by fernandodiacenco** [comment]
Oh amazing! I'm itching to replace our ticketing system with Lavagna, but the email feature is critical

Is there anywhere I can subscribe my email to receive Lavagna news/updates?

Thanks!

**Comment by SitoCH** [comment]
At the moment we only use our Twitter account ([@digitalfondue](https://twitter.com/digitalfondue)) to publish updates.

**Comment by erost** [comment]
This will be included in Pre-Release 1.1-M4. Documentation has been added in the internal Help, section 3.12
