### ISSUE TITLE
deploy on wildfly 10

### ISSUE THREAD

**Issue by mmghasemi** [digitalfondue/lavagna#34]
Hi to all
I try to deploy lavagna on wildfly, I am successful...
I added jboss-web.xml to WEB-INF and compile project with this new file,
In my jboss-web.xml file i decler vitual host:

```
<?xml version="1.0" encoding="UTF-8"?>
<jboss-web>
    <context-root>/</context-root>
    <virtual-host>lavagna</virtual-host>
</jboss-web>
```

 but when i deploy it on a wildfly and complete setup process on lavagna, redirect to main domain! instead to main path of project...So i see Not Found page...

**Comment by mmghasemi** [comment]
In server.log didn't report any error our warning.
What's the problem?

**Comment by syjer** [comment]
Hi, @mmghasemi , it looks like the configured domain is not correct. 

We will try to reproduce the error and check what's wrong.

**Comment by mmghasemi** [comment]
thanks
But my jboss-web.xml file work fine in other web application.
I couldn't deploy lavagna without jboss-web.xml on wildfly, but when add jboss-web.xml to project, it deploy successfully but as i said in above, i see Not Found page...

**Comment by syjer** [comment]
@mmghasemi , thanks for the additional information.

As we are not using widlfly it will take some time to understand the issue and, if there is a bug, to fix it.

Maybe, could you provide a step by step guide with some screenshots so we can more easily reproduce your issue?

**Comment by mmghasemi** [comment]
Thanks for attention.
Step 1:I cloned from lavagna github repositry!
Step 2:I changed some source of lavagna for example i18n files!
Step 3:I added jboss-web.xml to project
Step 4:I define virtual host in standalone.xml file on wildfly
`<host name="lavagna" alias="ketabfish.ir, www.ketabfish.ir" default-web-module="lavagna"/> `
Step 5:I access to http://ketabfish.ir domain to open project but!!!!
Username and password: mnm

**Comment by mmghasemi** [comment]
I think io.lavagna.web.support.ResourceController  may has some problem with contextpath in domain mode?

**Comment by syjer** [comment]
hi @mmghasemi , thanks for the informations. We have currently 2 issues:

Missing "index page": in web.xml, adding

```
    <welcome-file-list>
        <welcome-file>index.html</welcome-file>
        <welcome-file></welcome-file>
    </welcome-file-list>
```

Seems to fix it.


And the second one is some kind of error in the javascript concatenated file generation, this one will take some time to fix it

**Comment by syjer** [comment]
@mmghasemi , we have pushed some fixes, could you try to update your git clone and do a retry ?

Thank you :)

**Comment by mmghasemi** [comment]
@syjer Thank you,
Its work.
I pull from git and rebuild project and deploy on wildfly again and all things is ok...
