### ISSUE TITLE
Cyrillic text saves incorrectly

### ISSUE THREAD

**Issue by budrom** [digitalfondue/lavagna#35]
Greetings,
When using cyrillic anywhere in text fields, it is saved as question marks in database. If I select entry from LA_PROJECT table for example - it still has question marks. I can update text with cyrillic using SQL (via terminal with utf8 encoding set) and it shows correctly via SQL and in Lavagna. But after I try to update from Lavagna - it saves incorrectly.

Description there should be: `тест`
```
mysql> select * from LA_PROJECT;                     
+------------+--------------+--------------------+------------------+---------------------+
| PROJECT_ID | PROJECT_NAME | PROJECT_SHORT_NAME | PROJECT_ARCHIVED | PROJECT_DESCRIPTION |
+------------+--------------+--------------------+------------------+---------------------+
|          2 | Demo         | DEMO               |                0 | ????                |
+------------+--------------+--------------------+------------------+---------------------+
1 row in set (0.00 sec)
```

* Lavagna 1.0.7.2
* MySQL 5.5.46-0+deb7u1
* Database created as instructed - with utf8 encoding

**Comment by syjer** [comment]
Hi @budrom ,

Thank for the report!

Well, that's embarassing :). We will fix it asap.

**Comment by syjer** [comment]
Hi @budrom , it seems the issue is caused by an incomplete jdbc connection string (we will fix the documentation).

Could you try to add `?useUnicode=true&characterEncoding=utf-8` to the connection string? (as described in http://stackoverflow.com/a/3275661).

**Comment by budrom** [comment]
Hi @syjer , it worked! Thanks!

**Comment by syjer** [comment]
your welcome. Thank you for opening the issue :).

We will fix the doc :)
