### ISSUE TITLE
update documentation/scripts for mysql jdbc connection string

### ISSUE THREAD

**Issue by syjer** [digitalfondue/lavagna#36]
we need to add `?useUnicode=true&characterEncoding=utf-8` everywhere a mysql jdbc connection string is defined.

As found in issue #35

**Comment by mmghasemi** [comment]
Please repair this parameters for database connection urls for this page:
http://help.lavagna.io/02-install/02-02-configuration.html#configuration

**Comment by syjer** [comment]
I've finally updated the website.

**Comment by ghaseminya** [comment]
Thanks @syjer
