### ISSUE TITLE
i18n for src/main/webapp/app-login/app-login.js

### ISSUE THREAD

**Issue by mmghasemi** [digitalfondue/lavagna#37]
Hi
Why src/main/webapp/app-login/app-login.js couldn't accept i18n ?
I add some new properties to message_en.properties for this page but when use theme in app-login.js file does not work?
example hosted here: http://ketabfish.ir

**Comment by syjer** [comment]
Hi @mmghasemi , you are right. It's an oversight on our side. We will fix it.

**Comment by syjer** [comment]
Hi @mmghasemi , I've pushed a first test for supporting i18n in the login page.

**Comment by mmghasemi** [comment]
Thanks @syjer for fast coding...
I pull and test.

**Comment by mmghasemi** [comment]
I thought some utf-8 encoding had some error in app-login.js
ÙØ§Ù Ú©Ø§Ø±Ø¨
http://iproman.ir

**Comment by syjer** [comment]
Hi @mmghasemi , as you may have noticed, the property files in java are not utf-8 by default, you may use an IDE (intellij for example) which convert the characters in the appropriate forms or use the `native2ascii` command (http://docs.oracle.com/javase/7/docs/technotes/tools/windows/native2ascii.html) which is bundled by default with the jdk to convert the file.

**Comment by mmghasemi** [comment]
Hi @syjer 
I used native2ascii command for change properties for support UTF-8, 
but in all page unicode characters is properly ok but in login page fail
you can login to page to see correct Unicode in dashboard and other pages
http://iproman.ir
username=mnm

**Comment by syjer** [comment]
thanks for the feedback, I'll have a look.

**Comment by mmghasemi** [comment]
thanks

**Comment by syjer** [comment]
Ok, I'm able to reproduce the error, I'll commit a fix as soon as possible

**Comment by syjer** [comment]
@mmghasemi , I've pushed the fix :). Could you try to check if it work correctly ?

**Comment by mmghasemi** [comment]
thanks,
Yes...i pull and check it again...

**Comment by mmghasemi** [comment]
Its OK.
