### ISSUE TITLE
Role with access to certain project

### ISSUE THREAD

**Issue by mmghasemi** [digitalfondue/lavagna#39]
Hi
Can a role access only certain projects?
What class must change to create a new role with this feature?

**Comment by SitoCH** [comment]
It's a bit counterintuitive but yes, you can limit roles to see only some projects.
The first thing to do is remove the READ permission under "Board Permissions" on the default role (or create a new one without the READ permission) and then assign this application wide role to the selected users.
Now under every project that you wish to assign to those users just create a new role with the READ permission and assign it to them.

**Comment by mmghasemi** [comment]
Thanks SiteCH
it works...
why you said "its a bit counterintuitive"?

**Comment by SitoCH** [comment]
Because you have to remove the global "READ" permission on the default Role so it's easy to miss it when searching for a way to handle per project READ access.
