### ISSUE TITLE
Milestone editing (setting section)

### ISSUE THREAD

**Issue by leader80** [digitalfondue/lavagna#4]
Hi Crew,

while editing a milestone it shows a tick, once editing of the label is done I tried to save it with the tick, but without success. If I go away from the side and I come back the change is lost.

Cheers
L

EDIT: actually the tick doesn't do anything

![tick](https://cloud.githubusercontent.com/assets/73665/6918462/2f49aa92-d7af-11e4-9377-0cf995df1995.jpg)

**Comment by syjer** [comment]
Most likely a role issue after my changes :(

https://github.com/digitalfondue/lavagna/blob/db724d35333732c2592b3fc555aa63d5bad03df8/src/main/java/io/lavagna/web/api/CardLabelController.java#L151 the permission checked is Permission.PROJECT_ADMINISTRATION which your user should have.

**Comment by syjer** [comment]
should be fixed and deployed on openshift, thanks for the report :D

**Comment by leader80** [comment]
It is saving the new value, anyway I think it could be nice to inform the user of the stressfulness of the action, right now no message is shown.

**Comment by syjer** [comment]
cleanup issues :)
