### ISSUE TITLE
Short name uniquely not work properly

### ISSUE THREAD

**Issue by mmghasemi** [digitalfondue/lavagna#40]
Hi
I thinks main constraint for checking uniquely  short name at board creating has some error, because it compare with all short name in database not on project's short names.

**Comment by syjer** [comment]
Hi @mmghasemi , it's not an error but rather an explicit design choice.

**Comment by mmghasemi** [comment]
:)
yes this is a good choice, can i help you?

**Comment by SitoCH** [comment]
I'm closing the issue because this is a "by design" behaviour.
Feel free to reopen it if you need to add something else.
