### ISSUE TITLE
Where did save user's password?

### ISSUE THREAD

**Issue by ghaseminya** [digitalfondue/lavagna#41]
Hi
I searched for attribute password in LA_USER table, but no attribute for this job.
In profile, need change password function!

**Comment by syjer** [comment]
Hi @mmghasemi , well, Lavagna currently does not have a "user+password" support. It delegate the password/account handling to : oauth (google, gitlab, ...) or ldap.

The "demo" user account type is, as it's name imply, a demo feature :).

If you need an internal management of the user with password handling, it's a work in progress.

**Comment by mmghasemi** [comment]
oh, yes
thanks for @syjer 
I forgot this feature, oauth is very good choice
but i think demo user account type need password field...

**Comment by erost** [comment]
fixed as part of #73
