### ISSUE TITLE
add option to configure the application parameters in a property file

### ISSUE THREAD

**Issue by syjer** [digitalfondue/lavagna#43]

**Comment by mmghasemi** [comment]
Hi @syjer 
This is better way for connection to db in Tomcat...

**Comment by syjer** [comment]
implemented :)

**Comment by ejouvin** [comment]
Just got the last code version and compile it.
OK it seems to work to get the external property file, thanks.

(I have difficulties to initialise the database, but I will post on the previous thread, for the Tomcat install because someone else had difficulties)
