### ISSUE TITLE
Mysql database creation not completed on fresh install

### ISSUE THREAD

**Issue by ejouvin** [digitalfondue/lavagna#45]
Hello.

Just pickup the last commited files and do a fresh install.
After configuration, I can conect on the application.
But I have an error message displayed : "Connection failure. Please reload the page."
This message is displayed on Chrome but not IE 11

But in fact, the trace show the following error :
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [SELECT * FROM LA_PROJECT_MAIL_TICKET_CONFIG]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLS
yntaxErrorException: Table 'lavagna.LA_PROJECT_MAIL_TICKET_CONFIG' doesn't exist

It seems that some scripts were not executed, from the 17th.

**Comment by ejouvin** [comment]
I just run all missing script.

It remove error message in logs, so fine.

But the message is still displayed on the page, and only on Chrome

**Comment by syjer** [comment]
@ejouvin , about the "Connection failure. Please reload the page."  error, are you using a reverse proxy (ngnix?)

**Comment by ejouvin** [comment]
I think I should have create another issue for the error message after connection in fact.

I did test behind an Apache server. I will test with a direct connection on Tomcat.
But I fact, the connection is OK, and I just have a message in the bottom left corner and only on Chrome

**Comment by syjer** [comment]
if it's behind a proxy, it's possible that you need to add additional configurations, as lavagna use websockets.

**Comment by ejouvin** [comment]
It seems to be that.
I've just test to connect directly on tomcat and it works.

I remember to have seems an exampe of configuration in your doc (but I may be wrong...) but do not find it anymore.

**Comment by ejouvin** [comment]
I think we can close this issue.

The main topic, about the database creation, is solved.
The other one is linked to the case #46 , when deployed behind an Apache server + SSL + for sure a problem of websocket configuration in Apache
