### ISSUE TITLE
Invalid URL access with IE

### ISSUE THREAD

**Issue by ejouvin** [digitalfondue/lavagna#48]
Try to never use IE, but just one time I did a try.

And I was surprise to see the following Network activity :

![network](https://cloud.githubusercontent.com/assets/8817923/22014390/b9cc97ac-dc9d-11e6-82fe-e307c8859bcc.png)

It seems that IE does not like the commented line in file webapp\js\angular-material.min.js
//# sourceMappingURL=/home/sylvain/Downloads/tmp/output/angular-material.min.js

**Comment by syjer** [comment]
Hi @ejouvin , thanks for opening the issue, it's an oversight :). I'll push a fix as soon as possible.

**Comment by syjer** [comment]
done :)
