### ISSUE TITLE
Heavy traffic in case of error ?

### ISSUE THREAD

**Issue by ejouvin** [digitalfondue/lavagna#49]
Has I was testing the application, I notice heavy traffic.

Some background on my install.
Lavagna deployed under Tomcat
Add an Apache proxy

Application can be accessed with an url like http://server/lavagna
**Important to note** the application is not at root level.

I got one error, this url was reached :
http://server/mwg-internal/internal/progress?id=lM00ySujC71TPgjYHv2nAhH90WpT-G8Vb84GE8RocPM,

This URL can not be reached (may be because of provider policy but this is not the point) and then after I got an heavy heavy traffic on 
http://server/lavagna/api/socket/202/tiu2l0qt/xhr_streaming?t=1484735291353

It was about 83 requests during only 10 seconds.

**Comment by syjer** [comment]
the mwg-internal/internal/ url seems related to McAfee ? Looks like it block the websocket and then lavagna fall back to xhr_streaming, which, as you noticed,  is not optimal :)

**Comment by ejouvin** [comment]
Yes it may be McAfee you are right.

But then request on xhr_streaming have an 200 but the message is :
c[2010,"Another connection still open"]

It makes me reminder that I saw that also when I restart Apache Server. Connected user (in fact me) have this heavy traffic.

Not really blocking for me, just to mention it.

**Comment by SitoCH** [comment]
I’m closing this issue because it has been inactive for too long, please reopen it if you still encounter this issue.
