### ISSUE TITLE
Error by removing a role

### ISSUE THREAD

**Issue by leader80** [digitalfondue/lavagna#5]
Hi Crew,

under the setting section I cannot remove a custom role.

![error](https://cloud.githubusercontent.com/assets/73665/6963328/2ead2d3a-d93e-11e4-80da-ea0e3eb90e19.png)

**Comment by syjer** [comment]
Nice catch, we forgot to call the removal of the permission of a roles.

From the log:

```
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationExce
ption: Cannot delete or update a parent row: a foreign key constraint fails (`la
vagna`.`LA_PROJECT_ROLE_PERMISSION`, CONSTRAINT `LA_PROJECT_ROLE_PERMISSION_ibfk
_1` FOREIGN KEY (`PROJECT_ROLE_ID_FK`) REFERENCES `LA_PROJECT_ROLE` (`PROJECT_RO
LE_ID`))
```

We need to do that for both project related roles and base roles.

**Comment by syjer** [comment]
deployed on openshift

**Comment by syjer** [comment]
cleanup issues :)
