### ISSUE TITLE
Wrong URL to access the help

### ISSUE THREAD

**Issue by ejouvin** [digitalfondue/lavagna#50]
Hello.

In case the application is accessible behind Apache, and with an url like http://server/lavagna (not at root)
the help from the left panel will redirect to URL http://server/help

All other actions from the panel are correct, with something like http://server/lavagna/XXX

**Comment by syjer** [comment]
Thanks for the bug report :), I've pushed a fix.

**Comment by ejouvin** [comment]
👍 

Yes It works now.
But it could be nice if the Help is opened in a new window.

**Comment by syjer** [comment]
@ejouvin yes, you are right :), I've pushed the change.
