### ISSUE TITLE
Missing label message whild verify LDAP in administration

### ISSUE THREAD

**Issue by ejouvin** [digitalfondue/lavagna#51]
I did some tests and found that there is some missing labels when I wanted to verify LDAP setting from the administration panel.

On the popup windows where we type login & password.
![verify ldap](https://cloud.githubusercontent.com/assets/8817923/22128920/67fa8922-dea3-11e6-92d1-5b2a58582bed.png)

An after verification, there si still some missing labels.
![verified ldap](https://cloud.githubusercontent.com/assets/8817923/22128968/a23a2a8e-dea3-11e6-9f2c-2fc82d0338bd.png)

Regards.

**Comment by syjer** [comment]
Thanks for the issue :), we had some refactoring so some key went missing, will fix it.

**Comment by syjer** [comment]
should be fixed :)

**Comment by ejouvin** [comment]
👍 
Yes it is fixed.
