### ISSUE TITLE
Unable to authenticate on LDAP without user previously created

### ISSUE THREAD

**Issue by ejouvin** [digitalfondue/lavagna#52]
On my instance, I configured the LDAP.

My first account can acces the application, everything working fine.

But another user can not authenticate until its account was created from the administration panel.

It would be nice if the user could be automatically created, if it meet the LDAP configuration (and may be all other Oauth providers)

**Comment by syjer** [comment]
@ejouvin agree, it's something that will be done (available as an option, I don't think it should be enabled by default for Oauth providers)

**Comment by syjer** [comment]
should be implemented :)
