### ISSUE TITLE
Incorrect tooltip in titlebar

### ISSUE THREAD

**Issue by ejouvin** [digitalfondue/lavagna#55]
In the titlebar, there is some buttons.
A custom tooltip is displayed when the mouse is over.

But there is also a standard tooltip display, with a sort of key.
Moreover, the message is always the same : title.calendar

![tooltip error](https://cloud.githubusercontent.com/assets/8817923/22132027/b93ad65c-deb7-11e6-8a01-582592f8b947.png)

And just after the issue creation, I am not able to reproduce it.
If apends again, I will update the card.

**Comment by syjer** [comment]
@ejouvin thanks, I think that I've found the culprit, I'll do a fix

**Comment by syjer** [comment]
Should be fixed, thanks for opening this issue :)
