### ISSUE TITLE
Milestone, due_date display

### ISSUE THREAD

**Issue by ejouvin** [digitalfondue/lavagna#57]
When setting a due date on a milestone.
On the milestone, the date is displayed like Jan 31, 2017

But in milestones section, under Project board, the due date is displayed with hour information,  like 
2017-01-31T23:00:00:00Z

May be nice to have the same formatting as the one on the milestone instance ?

**Comment by syjer** [comment]
you are right, will fix it :+1:

**Comment by syjer** [comment]
Should be fixed, thanks :)

**Comment by ejouvin** [comment]
👍
