### ISSUE TITLE
Invalid calendar URL display in the profile

### ISSUE THREAD

**Issue by ejouvin** [digitalfondue/lavagna#58]
When Lavagna is accessible throw an URL like : http://SERVER/lavagna

When I access my profile, the calendar feed URL is something like : http://SERVER/api/calendar/XXXXXXXXXXXXXXXXXXXXX/calendar.ics

But it should be :
http://SERVER/lavagna/api/calendar/XXXXXXXXXXXXXXXXXXXXX/calendar.ics

**Comment by syjer** [comment]
good finding, I'll fix it :)

**Comment by syjer** [comment]
should be fixed now, thanks :) (and the url change when you reset the token)

**Comment by ejouvin** [comment]
👍
