### ISSUE TITLE
Profile notification parameters does not saved

### ISSUE THREAD

**Issue by ejouvin** [digitalfondue/lavagna#59]
On my instance, in the "My Profile" page, both notification parameters are not correctly saved. Even if checkbox are selected, options are not enabled.

The saving request payload is something like :{"email":"MY EMAIL","displayName":"MY NAME","emailNotification":true,"skipOwnNotifications":true}

And then the GET request on /api/self contains the following:
"userMetadata":{"showArchivedProjects":false,"showArchivedBoards":false},"id":2,"provider":"ldap","username":"MY LOGIN","email":"MY EMAIL","displayName":"MY NAME","emailNotification":false,"memberSince":"2017-01-12T23:07:44.000Z","skipOwnNotifications":false}

I checked on the database, value stored are false.

**Comment by syjer** [comment]
Hi @ejouvin , you are right, we will fix it asap!

**Comment by syjer** [comment]
pushed the fix, thank you!

**Comment by ejouvin** [comment]
👍
