### ISSUE TITLE
[Feature Request] - Web based configurations wizard

### ISSUE THREAD

**Issue by vClouds** [digitalfondue/lavagna#60]
It is really difficult for non-java knowledge people like me trying to get around installation with production using mysql.

I kept moving between JDK 8 and 7, tomcat, wildfly and jetty experiencing all kinds of errors ending with "command not found" outputs while trying just to pass the environment properties.

I hope, configuration wizard to be introduced so that profile properties can be passed.
I'm not sure if that approach would be applicable with java apps or not.

Another idea, is hacking pom.xml file to alter the prod profile as default can help?

```
	<profile>
			<id>prod</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<properties>
				<fast-build>false</fast-build>
				<jetty.port>8080</jetty.port>
				<jetty.host>0.0.0.0</jetty.host>
				<datasource.dialect>MYSQL</datasource.dialect>
				<!-- <datasource.driver>net.sf.log4jdbc.sql.jdbcapi.DriverSpy</datasource.driver> -->
				<!-- <datasource.url>jdbc:log4jdbc:hsqldb:mem:lavagna</datasource.url> -->
				<datasource.url>jdbc:mysql://.....:lavagna</datasource.url>
				<datasource.username>lavagna</datasource.username>
				<datasource.password />

```
  
Please advise.

**Comment by SitoCH** [comment]
Hi,
I assume that you are trying to run Lavagna from a cloned repository and in order to use it with MySQL you don't have to change anything, just run the following commands and you should be up and running:

```
mvn clean install
java -Ddatasource.dialect=MYSQL -Ddatasource.url=jdbc:mysql://server/lavagna?useSSL=false -Ddatasource.username=sa -Ddatasource.password=pwd -Dspring.profiles.active=prod -jar target/dependency/jetty-runner.jar --port 8080 target/*.war
```
