### ISSUE TITLE
Missing day in Calendar

### ISSUE THREAD

**Issue by ejouvin** [digitalfondue/lavagna#61]
As I was watching my Calendar on January 2017, I noticed there is some missing days.

![image](https://cloud.githubusercontent.com/assets/8817923/22439724/156f818a-e731-11e6-89cd-3d07a7fd48d5.png)

But 30st and 31st are displayed as expected on February
![image](https://cloud.githubusercontent.com/assets/8817923/22439752/2a07fb4a-e731-11e6-89bb-ca9a63a26d33.png)

But may be, this is "expected" in order to have a fixed number of line in the calendar ?

**Comment by syjer** [comment]
oh, good find, we will fix it, as it's kinda strange :D

**Comment by SitoCH** [comment]
Hi,
unexpectedly the number of days in a month was capped at 30. It's funny because also the demo of the original component has the same bug...
Fixed and thank you for reporting this issue.

**Comment by ejouvin** [comment]
👍 
It works for me.
