### ISSUE TITLE
Timestamp issue, at least in comments

### ISSUE THREAD

**Issue by ejouvin** [digitalfondue/lavagna#70]
On my current install.

Server is on Paris time.
Computer is on Paris time.

But when I added a comment, the displayed time is not correct.
![image](https://cloud.githubusercontent.com/assets/8817923/22764222/901cefe6-ee69-11e6-9785-c65b6577466f.png)

The date stored in the database is the one from my local computer, so in Paris Time.
But when displayed, there is +1 hour, as if the stored time is considered as UTC.

Etienne

**Comment by syjer** [comment]
I'm able to reproduce the issue, will fix it :)

**Comment by syjer** [comment]
should be fixed :)

**Comment by ejouvin** [comment]
And it is fixed 👍
