### ISSUE TITLE
User / Project Management / Deleting Users and Projects

### ISSUE THREAD

**Issue by quirinfischer** [digitalfondue/lavagna#72]
Hello Lavagna Team,
I have a few suggestions for additional features:

- extra role for managing everything in Lavagna (**super admin**)
It would make administration much easier if one super admin could change user names, passwords, email addresses. Right now only the user itself can change these tokens. 

- **deleting user** or moving them to an inactive panel
When starting Lavagna I was creating test users to check if everything was working. Now I can not remove them anymore. I would like to delete users who are either test users or leaving the project.

- **deleting whole projects**
I can not find a feature to delete e.g. the test test project which is the default project to show Lavagnas features. Also whenever I create a new project I can not remove it anymore (only archive).

Regards,
Quirin

**Comment by erost** [comment]
Hi @quirinfischer ,

thanks for your feedback!

> extra role for managing everything in Lavagna (especially users)
We plan to add a new internal provider (link: #71), so the users that have access to the admin panel will be able to reset the password for those users (in case of external auth provider, that's not possible as Lavagna doesn't directly manage those users, just allow them to login). We will discuss about allowing admins to change display name/email addresses.

> deleting user/inactive panel
I like the idea of adding a filter for active/inactive users to declutter the UI. Deleting users creates all sorts of issues with data ownership, and if a user ever comes back to a project it's nice to still have the old stuff available

> deleting whole projects
in 1.1, a show/hide archived boards/projects has been added to declutter the UI. This is a temporary measure to alleviate the pain of having multiple inactive items. Delete a project is in the roadmap, but may not make it in 1.1

**Comment by quirinfischer** [comment]
Hi @erost ,
thanks for your fast response.
I am excited for the new features.

**Comment by erost** [comment]
this has been addressed in #73
