### ISSUE TITLE
"Send test E-Mail" does nothing

### ISSUE THREAD

**Issue by sebastianopilla** [digitalfondue/lavagna#75]
Lavagna 1.1M3 on PostgreSQL.

In the Admin Panel, when configuring the SMTP server for the email notifications, there's a "Send test E-Mail" button which brings up a dialog box: I can enter an email address and click "Send test E-Mail", however no email is sent.

Lavagna does not attempt to connect to the configured SMTP server, and by looking at the HTTP traffic in the browser's console there's no request made from this button to the Lavagna server to the api/check-smtp/ endpoint, which is what I expected after looking at the code.

The issue is 100% reproductible for me, on both Firefox and Chrome (latest versions) on Fedora Linux 25. The server is running CentOS 7.3 on Oracle JDK 1.8.0_121.

**Comment by syjer** [comment]
Hi @sebastianopilla , thank you for opening this issue, I think we have fixed it in the eslint branch. When we will merge it in the master, we will do a M4 release :)

**Comment by syjer** [comment]
should be fixed in the now released M4.
