### ISSUE TITLE
Advanced card creation

### ISSUE THREAD

**Issue by ejouvin** [digitalfondue/lavagna#79]
Hello.

When I want to add a new card, I only see a simple form.
![image](https://cloud.githubusercontent.com/assets/8817923/25507950/48e04fc8-2baf-11e7-8cae-afa7e19a0e88.png)

But it could be interesting to have the advanced card form, like when we modify it.
Because for now, I must create the card, then open it. For one card, it is fine, but if I want to create 10 or more, it is time consuming

**Comment by syjer** [comment]
Hi @ejouvin ,

Yep, thanks for the idea, it's something that will be implemented in a future release.

**Comment by erost** [comment]
@ejouvin this has been released with 1.1-M6 if you want to test it out.

**Comment by ejouvin** [comment]
Just installed the new version.

I like the fact that things are kept, like labels.

It seems OK for me.

Thanks.
