### ISSUE TITLE
Dropbox or Google Drive Integration

### ISSUE THREAD

**Issue by pinecreativelabs** [digitalfondue/lavagna#80]
I think it would be cool to have a way for either Dropbox or Google Drive (or both) integrated in some way. This would create a way for users to share files.

For each task, a user could attach Dropbox files, or Google Drive files. 

Thoughts?

**Comment by syjer** [comment]
Hi @pinecreativelabs , could you elaborate the use case? (What are the user actions, what would be the expected result)

Currently I'm not able to understand what would be benefit, thank you :)
