### ISSUE TITLE
csv card export

### ISSUE THREAD

**Issue by superkekko** [digitalfondue/lavagna#86]
Is it possible to have a csv (or json) export of all the card in a board with all the properties (status, due date, create date, assingn to, and lables)?

**Comment by syjer** [comment]
I guess that we could add it, as we already have an export to "excel" :) 👍

**Comment by superkekko** [comment]
Awesome because my client want a report of the tasks. Thanks.

**Comment by SitoCH** [comment]
At the moment you can export everything to Excel and from there export it again to CSV.
If you are using Lavagna 1.0.X you can find the button in the project's administration page, with version 1.1.X it's on the project's main page, right after the title.

**Comment by superkekko** [comment]
Awesome. Is it possibile to have in that export also the due date, create date, assingn to, and lables?

**Comment by SitoCH** [comment]
Yes, I think that the only field that isn't exported is the "creation date", all the others should be exported in the Excel.

**Comment by superkekko** [comment]
Yes. I've checked in another project and is perfect. Thanks.

**Comment by SitoCH** [comment]
I'm closing this issue because the required columns have been included.
