### ISSUE TITLE
Suggestions to improve Lavagna versatility as ticketing system

### ISSUE THREAD

**Issue by fernandodiacenco** [digitalfondue/lavagna#88]
Hi there!

I'm using Lavagna 1.1 m7 as everyday work tool , it can't replace our current ticketing system (yet) but I will leave a few suggestions hoping this can be achieved in the future

1) Word wrap can be improved a little perhaps instead of cutting half the word it adjusts it on the next line, see:
![improve_wordwrap](https://user-images.githubusercontent.com/2643364/29772987-b109f04a-8bd1-11e7-9520-21d56c35a719.png)

2) A reply button for cards coming by mail and signature support
![reply](https://user-images.githubusercontent.com/2643364/29773032-f05f0f8c-8bd1-11e7-800c-ac0e8598b48c.png)

This would open a simple reply popup just enough to be used for sending and email instead of using and external mail client, with html or image signature support, just for convenience

The email interactions could be saved in the comments section, a problem i can see with that is that the email must have some unique identifier (subject being the card title or something) otherwise the end user can't create two different cards

3) End user notifications:
This would function as a notification for the end user, when a card was created an email is sent back with something like "Your ticked **(CARDTITLE)** has been opened, we will be in contact shortly, etc etc"

4) End user view only:
Now this is a little tricky for me to explain. Imagine that with the notification came something like "to view your ticket status click here **(link)**" and when clicked this link provides a view only link for the end user, so see only the cards he created, so if john doe has a problem, he received a link http://lavagna/it/support/view/john.doe@company.com so he can see where all his cards are (columns) BUT only his cards

_BUUUUT_ this creates another problem, any user could see each others tickets if simply changing the link to include other email, this could be mitigated by encoding the url with something, so what the user sees is something like http://lavagna/it/support/view/am9obi5kb2VAY29tcGFueS5jb20=

I understand many of those suggestions might not be achievable, but at the very least serves as food for thought

Thanks!

**Comment by syjer** [comment]
Hi, @fernandodiacenco , thanks for the feedback 👍 .

I think that generally all your suggestions are feasible :). We will try to implement them bit by bit :)

**Comment by syjer** [comment]
by the way, the email notification on creation already exists. You can customize the message too (see the documentation https://github.com/digitalfondue/lavagna/blob/master/src/main/stampo/doc/03-use-lavagna/03-12-ticket-mail.en.peb.md )
