### ISSUE TITLE
attachment error

### ISSUE THREAD

**Issue by superkekko** [digitalfondue/lavagna#90]
Hi, when I attach to a card a big file (over 5Mb) despite the loaded message when I reopen the card the file is only 1b.

**Comment by syjer** [comment]
Well, that's strage, which database are you using? Did you set a max file size in the configuration?

**Comment by superkekko** [comment]
mysql as DB. I didn't install the application my colleague did. Where is the settings? I can check.

**Comment by syjer** [comment]
In the "Admin Panel", first panel: "Configuration Parameters", there is an input where you can set the max size in bytes.

**Comment by superkekko** [comment]
I don't have that configuration paramiter

![error](https://user-images.githubusercontent.com/25342565/29882374-164acf42-8dad-11e7-9e39-52570ea86b4b.png)

**Comment by SitoCH** [comment]
It's the second field from the top: `Max upload file size (in bytes)`.
If I remember correctly there may also be some connection string parameter to adjust in order to allow bigger package sizes.

**Comment by superkekko** [comment]
Thanks. I thought that value was for Trello. I will check.

**Comment by superkekko** [comment]
All good, thanks.
