### ISSUE TITLE
Cannot get Lavagna to start with MySQL

### ISSUE THREAD

**Issue by c0mputerking** [digitalfondue/lavagna#96]
I guess i am a total java newbie, i know, i know, everyone hates a newb but i cannot get Lavagna to start with MySQL.  Probably missing something really obvious, but cannot figure it out so thought it would put up an issue here details below. 

NOTE I can get Lavagna to running with HSQLDB but it does not store anything as per the design i suppose, It looks really great, more on that later, and i cannot wait to get started entering my permanent data :)  Howver I have tried with "-Ddatasource.url=jdbc:hsqldb:file:lavagna" but get an error and Lavangna refuses to start, rather than waste time troubleshooting HSQLDB I would rather just make MySQL work.

Some background;
Running a fully up to date version of Debian 9  ( lxc so i am not tied to Debian 9, and can use whatever distro works best/easiest ) including
     mysqld 10.1.26-MariaDB-0+deb9u1
     java-8-openjdk-amd64

Using the milestone release Lavagna-1.1-M7 with the default lavagna.sh as below works

```
BASEDIR=$(dirname $0)
 
java \
        -Ddatasource.dialect=HSQLDB \
        -Ddatasource.url=jdbc:hsqldb:mem:lavagna \
        -Ddatasource.username=sa \
        -Ddatasource.password= \
        -Dspring.profiles.active=prod \
        -jar $BASEDIR/../lavagna/lavagna-jetty-console.war
```

However testing with MySQL as in the config farthest below is not working and gives the error below, of course i tried commenting out the username and password lines but then get the error even further below sorry for my ignorant post but please help as Lavagna looks to be really fantastic and cannot wait to get using it and some issues that might actually improve Lavagna   

**./lavagna.sh: line 78: -Ddatasource.username=c0mputerking: command not found
./lavagna.sh: line 82: -Dspring.profiles.active=prod: command not found**

```
BASEDIR=$(dirnam#e $0)
 
java \
       -Ddatasource.dialect=MYSQL \
       -Ddatasource.url=jdbc:mysql://localhost:3306/lavagna?useUnicode=true&characterEncoding=utf-8 \
       -Ddatasource.username=someuser \
       -Ddatasource.password= somepassword \
       -Dspring.profiles.active=prod \
       -jar $BASEDIR/../lavagna/lavagna-jetty-console.war
```

**Comment by SitoCH** [comment]
Hi,
did you try to put the `"` around every parameter? It should look like this:

```
BASEDIR=$(dirnam#e $0)
 
java \
       -Ddatasource.dialect="MYSQL" \
       -Ddatasource.url="jdbc:mysql://localhost:3306/lavagna?useUnicode=true&characterEncoding=utf-8&useSSL=false" \
       -Ddatasource.username="someuser" \
       -Ddatasource.password="somepassword" \
       -Dspring.profiles.active="prod" \
       -jar $BASEDIR/../lavagna/lavagna-jetty-console.war
```

**Comment by c0mputerking** [comment]
Thank you for your help :)
I tried putting everything in double quotes, and get a new error now see below could be progress :) 

NOTE the only command i used to setup my database is this "CREATE DATABASE lavagna CHARACTER SET utf8 COLLATE utf8_bin;" found in you help section is that enough to get things going as there is probably no username or password yet?

> bin# ./lavagna.sh
> Error: Could not find or load main class somepassword

Here is what i have in my config lavagna.sh file now

```
BASEDIR=$(dirname $0)

java \
        -Ddatasource.dialect="MYSQL" \
        -Ddatasource.url="jdbc:mysql://localhost:3306/lavagna?useUnicode=true&characterEncoding=utf-8" \
        -Ddatasource.username="someuser" \
        -Ddatasource.password= "somepassword" \
        -Dspring.profiles.active="prod" \
        -jar $BASEDIR/../lavagna/lavagna-jetty-console.war
```

**Comment by SitoCH** [comment]
Maybe it's due to the whitespace between `-Ddatasource.password=` and `"somepassword"`, if you remove it do you see the same error?

**Comment by c0mputerking** [comment]
Yep that fixed it :) THANK YOU what a silly mistake on my part sorry 
 
Bye the way thank you again for your help and a huge thank you for Lavagna looks so incredibly awesome i am super excited to start using it now.  The feature set looks like an almost perfect match to what i have been looking for amazing it's like you folks read my mind :)

Have been looking for something like this for years, have tried several others trying to find a selfhosted and opensource solution.  Tiaga, Wekan, Restyaboard, Tuleap, Taskboard, etc, etc, etc, etc, and have been using Kanboard for a couple of years none are quite right for my needs.

Lavagna looks, and feels very professional, and polished, very usable i could go on about how great Lavangna is, but i want to start using it now instead of writing this issue :)

**Comment by SitoCH** [comment]
Thank you very much for the compliments, I'm glad that your issue is now resolved.
