### ISSUE TITLE
change BASE_APPLICATION_URL ?

### ISSUE THREAD

**Issue by c0mputerking** [digitalfondue/lavagna#98]
Is there a way to change the BASE_APPLICATION_URL i installed Lavagna on several test VM's but want to move it into its proper DNS place now. For example i am now using http://lavagna-3.mydomain.com and would like to move it to https://lavagna.mydomain.com

Related to another issue i have opened [https://github.com/digitalfondue/lavagna/issues/97](url)
I may or may not need to change the http:// to https:// part of the BASE_APPLICATION_URL ... this is still unclear to me as i have not setup the reverse proxy yet.

**Comment by SitoCH** [comment]
As far as I remember you have to edit the database, there should be a config table somewhere.

**Comment by c0mputerking** [comment]
Took my awhile to get this done, and my mysql syntax is weak so i cheated and used phpmyadmin.
Here is the SQL needed to change BASE_APPLICATION_URL as it gets outputed by phpmyadmin and may come in handy for someone else.  Lastly thanks for the point in the right direction SitoCH 

UPDATE `LA_CONF` SET `CONF_VALUE` = 'https://list.solar.mydomain.com/' WHERE `LA_CONF`.`CONF_KEY` = 'BASE_APPLICATION_URL';

**Comment by SitoCH** [comment]
Yes, that is the right SQL statement to change the `BASE_APPLICATION_URL` setting, everything else should work fine.
